# hypridle.conf
# https://wiki.hypr.land/Hypr-Ecosystem/hypridle/

general {
    lock_cmd = pidof hyprlock || hyprlock   # only spawn if not already running
    before_sleep_cmd = loginctl lock-session
    after_sleep_cmd = hyprctl dispatch dpms on
}

# Dim screen warning at 4 min
listener {
    timeout = 603000
    on-timeout = brightnessctl -s set 20%
    on-resume = brightnessctl -r
}

# Lock screen at 5 min
listener {
    timeout = 604800
    on-timeout = loginctl lock-session
}

# Turn displays off at 8 min (after lock)
listener {
    timeout = 605100
    on-timeout = hyprctl dispatch dpms off
    on-resume = hyprctl dispatch dpms on
}

# Suspend at 30 min
listener {
    timeout = 608000
    on-timeout = systemctl suspend
}
